"""Add soft deletion to tags and role models

Revision ID: 12e9690fb3f0
Revises: 270bebe94c51
Create Date: 2024-04-12 23:48:55.417730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e9690fb3f0'
down_revision = '270bebe94c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.execute("UPDATE roles SET is_active = true")
    

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
