"""Add soft deletion to role model

Revision ID: 270bebe94c51
Revises: 83b84223a675
Create Date: 2024-04-12 23:32:03.010157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270bebe94c51'
down_revision = '83b84223a675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))

    op.execute("UPDATE document_types SET is_active = true")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ##
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
